@{
  ModuleVersion     = "1.0.0.0"
  GUID              = "7ef2a734-a882-4b6e-b3d9-2c43b1bdd3ed"
  NestedModules     = @(
    ".\New-Junction"
    ".\Set-Folder"
    ".\Get-FolderChildItem"
    ".\Invoke-Folder"
    ".\Edit-File"
    ".\Clear-Container"
    ".\Remove-Folder"
    ".\Get-Property"
  )
  FunctionsToExport = @(
    "New-Junction"
    "Get-SiblingItem"
    "Get-HomeItem"
    "Invoke-Folder"
    "Invoke-Parent"
    "Invoke-Home"
    "Invoke-Drive"
    "Edit-File"
    "Clear-Container"
    "Remove-Folder"
    "Get-Parent"
    "Get-FileSize"
  )
  AliasesToExport   = @(
    "mj"
    "c."
    "c.."
    "cd."
    "c~"
    "c\"
    "c/"
    "d\"
    "d/"
    "l."
    "l.."
    "ls."
    "ls.."
    "l~"
    "ls~"
    "explore"
    "e"
    "e."
    "e.."
    "e~"
    "e\"
    "e/"
    "i"
    "cl"
    "parent"
    "size"
  )
}
