@{
  RootModule           = 'Module.dll'
  ModuleVersion        = '3.0.0.0'
  CompatiblePSEditions = @('Desktop', 'Core')
  GUID                 = '0d6f7f29-9175-410d-bd89-622ad5926f29'
  Author               = 'Jimmy Zhening Luo'
  CompanyName          = 'Jimmy Zhening Luo'
  Copyright            = '(c) 2025 Jimmy Zhening Luo. All rights reserved.'
  PowerShellVersion    = '7.5'
  FunctionsToExport    = @()
  CmdletsToExport      = @(
    'Clear-Line'
    'Set-Directory'
    'Set-DirectorySibling'
    'Set-DirectoryRelative'
    'Set-DirectoryHome'
    'Set-DirectoryCode'
    'Set-Drive'
    'Set-DriveD'
    'Get-Directory'
    'Get-DirectorySibling'
    'Get-DirectoryRelative'
    'Get-DirectoryHome'
    'Get-DirectoryCode'
    'Get-DirectoryDrive'
    'Get-File'
    'Get-FileSibling'
    'Get-FileRelative'
    'Get-FileHome'
    'Get-FileCode'
    'Get-FileDrive'
    'Get-Size'
    'Start-Explorer'
    'Start-ExplorerSibling'
    'Start-ExplorerRelative'
    'Start-ExplorerHome'
    'Start-ExplorerCode'
    'Start-ExplorerDrive'
    'Start-Workspace'
    'Start-WorkspaceSibling'
    'Start-WorkspaceRelative'
    'Start-WorkspaceHome'
    'Start-WorkspaceCode'
    'Start-WorkspaceDrive'
    'New-Directory'
    'New-Junction'
    'Remove-Directory'
    'Stop-Task'
    'Edit-SystemPath'
    'Update-Windows'
    'Update-StoreApp'
    'Open-Url'
    'Test-Url'
    'Test-Host'
    'Copy-Guid'
    'ConvertTo-Hex'
    'Start-Profile'
    'Start-History'
    'Get-CommandAlias'
    'Get-VerbList'
    'Get-Type'
  )
  VariablesToExport    = @()
  AliasesToExport      = @(
    'cl'
    'clear'
    'c'
    'cx'
    'cxx'
    'ch'
    'cc'
    'c/'
    'd/'
    'l'
    'lx'
    'lxx'
    'lh'
    'lc'
    'l/'
    'p'
    'px'
    'pxx'
    'ph'
    'pc'
    'p/'
    'sz'
    'size'
    'e'
    'ex'
    'exx'
    'eh'
    'ec'
    'e/'
    'i'
    'ix'
    'ixx'
    'ih'
    'ic'
    'i/'
    'mk'
    'mj'
    'rd'
    'tkill'
    'path'
    'wu'
    'su'
    'o'
    'open'
    'tu'
    'tn'
    'gu'
    'guid'
    'hex'
    'op'
    'oc'
    'galc'
    'ty'
    'types'
  )
}
