@{
  RootModule        = 'Shell.psm1'
  ModuleVersion     = '3.0.0.0'
  GUID              = '195c0492-bfd4-4873-8c2b-c88f53c9b7e8'
  PowerShellVersion = '7.5'
  RequiredModules   = @(
    'Browse'
    'GenericArgumentCompleter'
  )
  NestedModules     = @(
    'Shell.New'
    'Shell.Clear'
    'Shell.Get'
    'Shell.Set'
    'Shell.Invoke'
  )
  FunctionsToExport = @(
    'Format-Path'
    'Test-Item'
    'Resolve-Item'
    'New-Directory'
    'New-Junction'
    'Clear-Line'
    'Remove-Directory'
    'Get-Size'
    'Get-Directory'
    'Get-DirectorySibling'
    'Get-DirectoryRelative'
    'Get-DirectoryHome'
    'Get-DirectoryCode'
    'Get-DirectoryDrive'
    'Get-File'
    'Get-FileSibling'
    'Get-FileRelative'
    'Get-FileHome'
    'Get-FileCode'
    'Get-FileDrive'
    'Set-Directory'
    'Set-DirectorySibling'
    'Set-DirectoryRelative'
    'Set-DirectoryHome'
    'Set-DirectoryCode'
    'Set-Drive'
    'Set-DriveD'
    'Invoke-Directory'
    'Invoke-DirectorySibling'
    'Invoke-DirectoryRelative'
    'Invoke-DirectoryHome'
    'Invoke-DirectoryCode'
    'Invoke-DirectoryDrive'
    'Invoke-Workspace'
    'Invoke-WorkspaceSibling'
    'Invoke-WorkspaceRelative'
    'Invoke-WorkspaceHome'
    'Invoke-WorkspaceCode'
    'Invoke-WorkspaceDrive'
  )
  CmdletsToExport   = @()
  VariablesToExport = @()
  AliasesToExport   = @(
    'touch'
    'mk'
    'mj'
    'cl'
    'split'
    'hash'
    'sz'
    'size'
    'l'
    'l.'
    'l..'
    'l~'
    'lc'
    'l/'
    'p'
    'p.'
    'p..'
    'p~'
    'pc'
    'p/'
    'c'
    'c.'
    'c..'
    'c~'
    'cc'
    'c/'
    'd/'
    'e'
    'e.'
    'e..'
    'e~'
    'ec'
    'e/'
    'i'
    'i.'
    'i..'
    'i~'
    'ic'
    'i/'
  )
}
