@{
  RootModule            = 'Shell.psm1'
  ModuleVersion         = '3.0.0.0'
  CompatiblePSEditions  = @('Desktop', 'Core')
  GUID                  = 'e4d07654-6759-4a2f-8293-39df2b809ba7'
  Author                = 'Jimmy Zhening Luo'
  CompanyName           = 'Jimmy Zhening Luo'
  Copyright             = '(c) 2025 Jimmy Zhening Luo. All rights reserved.'
  PowerShellVersion     = '7.5'
  PowerShellHostName    = 'ConsoleHost'
  PowerShellHostVersion = '7.5'
  RequiredModules       = @(
    @{
      ModuleName    = 'GenericArgumentCompleter'
      ModuleVersion = '3.0.0'
      GUID          = 'ce7965e6-f9ef-42fb-aa4b-80eb542833de'
    }
  )
  NestedModules         = @(
    @{
      ModuleName    = 'Shell.New'
      ModuleVersion = '3.0.0.0'
      GUID          = '9a3324b2-207d-4635-a8d6-ac8261181fb1'
    }
    @{
      ModuleName    = 'Shell.Clear'
      ModuleVersion = '3.0.0.0'
      GUID          = '7b39ad83-781d-49f2-a378-f913d983b1a6'
    }
    @{
      ModuleName    = 'Shell.Get'
      ModuleVersion = '3.0.0.0'
      GUID          = '83fda875-8f8c-4bce-a5da-e840d832378d'
    }
    @{
      ModuleName    = 'Shell.Set'
      ModuleVersion = '3.0.0.0'
      GUID          = 'e740b507-c756-4684-8565-8c579344e454'
    }
    @{
      ModuleName    = 'Shell.Invoke'
      ModuleVersion = '3.0.0.0'
      GUID          = '130b56d3-229a-4ec1-be75-d31a615147c8'
    }
    @{
      ModuleName    = 'Shell.Browse'
      ModuleVersion = '3.0.0.0'
      GUID          = '1e45c553-ea48-41c2-a7fc-89b5c36f30b1'
    }
  )
  FunctionsToExport     = @(
    'Format-Path'
    'Test-Item'
    'Resolve-Item'
    'New-Directory'
    'New-Junction'
    'Clear-Line'
    'Remove-Directory'
    'Get-Size'
    'Get-Directory'
    'Get-DirectorySibling'
    'Get-DirectoryRelative'
    'Get-DirectoryHome'
    'Get-DirectoryCode'
    'Get-DirectoryDrive'
    'Get-File'
    'Get-FileSibling'
    'Get-FileRelative'
    'Get-FileHome'
    'Get-FileCode'
    'Get-FileDrive'
    'Set-Directory'
    'Set-DirectorySibling'
    'Set-DirectoryRelative'
    'Set-DirectoryHome'
    'Set-DirectoryCode'
    'Set-Drive'
    'Set-DriveD'
    'Invoke-Directory'
    'Invoke-DirectorySibling'
    'Invoke-DirectoryRelative'
    'Invoke-DirectoryHome'
    'Invoke-DirectoryCode'
    'Invoke-DirectoryDrive'
    'Invoke-Workspace'
    'Invoke-WorkspaceSibling'
    'Invoke-WorkspaceRelative'
    'Invoke-WorkspaceHome'
    'Invoke-WorkspaceCode'
    'Invoke-WorkspaceDrive'
    'Test-Host'
    'Test-Url'
    'Open-Url'
  )
  CmdletsToExport       = @()
  VariablesToExport     = @()
  AliasesToExport       = @(
    'touch'
    'mk'
    'mj'
    'cl'
    'split'
    'hash'
    'sz'
    'size'
    'l'
    'l.'
    'l..'
    'l~'
    'lc'
    'l/'
    'p'
    'p.'
    'p..'
    'p~'
    'pc'
    'p/'
    'c'
    'c.'
    'c..'
    'c~'
    'cc'
    'c/'
    'd/'
    'e'
    'e.'
    'e..'
    'e~'
    'ec'
    'e/'
    'i'
    'i.'
    'i..'
    'i~'
    'ic'
    'i/'
    'tn'
    'tu'
    'go'
    'open'
  )
}
