@{
  RootModule           = 'Shell.psm1'
  ModuleVersion        = '3.0.0.0'
  CompatiblePSEditions = @('Desktop', 'Core')
  GUID                 = 'e4d07654-6759-4a2f-8293-39df2b809ba7'
  Author               = 'Jimmy Zhening Luo'
  CompanyName          = 'Jimmy Zhening Luo'
  Copyright            = '(c) 2025 Jimmy Zhening Luo. All rights reserved.'
  PowerShellVersion    = '7.5'
  RequiredModules      = @(
    @{
      ModuleName    = 'Completer'
      ModuleVersion = '3.0.0'
      GUID          = '95f00487-efc3-43e8-adcb-c539f28f0058'
    }
  )
  NestedModules        = @(
    @{
      ModuleName    = 'Shell.New'
      ModuleVersion = '3.0.0.0'
      GUID          = '9a3324b2-207d-4635-a8d6-ac8261181fb1'
    }
    @{
      ModuleName    = 'Shell.Get'
      ModuleVersion = '3.0.0.0'
      GUID          = '83fda875-8f8c-4bce-a5da-e840d832378d'
    }
    @{
      ModuleName    = 'Shell.Set'
      ModuleVersion = '3.0.0.0'
      GUID          = 'afed7375-abb6-4d62-9b11-fa07320220aa'
    }
    @{
      ModuleName    = 'Shell.Invoke'
      ModuleVersion = '3.0.0.0'
      GUID          = '130b56d3-229a-4ec1-be75-d31a615147c8'
    }
    @{
      ModuleName    = 'Shell.Remove'
      ModuleVersion = '3.0.0.0'
      GUID          = '1099153a-7f76-415c-8b8f-d18f5351d581'
    }
    @{
      ModuleName    = 'Shell.Code'
      ModuleVersion = '3.0.0.0'
      GUID          = 'a5751c41-5026-444f-8c2a-f13a2ac354f2'
    }
  )
  FunctionsToExport    = @(
    'Clear-Line'
    'Test-Item'
    'Resolve-Item'
    'New-Directory'
    'New-Junction'
    'Get-Size'
    'Get-Directory'
    'Get-DirectorySibling'
    'Get-DirectoryRelative'
    'Get-DirectoryHome'
    'Get-DirectoryCode'
    'Get-DirectoryDrive'
    'Get-File'
    'Get-FileSibling'
    'Get-FileRelative'
    'Get-FileHome'
    'Get-FileCode'
    'Get-FileDrive'
    'Set-Directory'
    'Set-DirectorySibling'
    'Set-DirectoryRelative'
    'Set-DirectoryHome'
    'Set-DirectoryCode'
    'Set-Drive'
    'Set-DriveD'
    'Invoke-Directory'
    'Invoke-DirectorySibling'
    'Invoke-DirectoryRelative'
    'Invoke-DirectoryHome'
    'Invoke-DirectoryCode'
    'Invoke-DirectoryDrive'
    'Invoke-Workspace'
    'Invoke-WorkspaceSibling'
    'Invoke-WorkspaceRelative'
    'Invoke-WorkspaceHome'
    'Invoke-WorkspaceCode'
    'Invoke-WorkspaceDrive'
    'Remove-Directory'
    'Invoke-GitRepository'
    'Measure-GitRepository'
    'Import-GitRepository'
    'Get-GitRepository'
    'Get-ChildGitRepository'
    'Add-GitRepository'
    'Write-GitRepository'
    'Push-GitRepository'
    'Reset-GitRepository'
    'Restore-GitRepository'
    'Invoke-Node'
    'Invoke-NodePackage'
    'Invoke-NodeExecutable'
    'Clear-NodeModuleCache'
    'Compare-NodeModule'
    'Step-NodePackageVersion'
    'Invoke-NodePackageScript'
    'Test-NodePackage'
  )
  CmdletsToExport      = @()
  VariablesToExport    = @()
  AliasesToExport      = @(
    'cl'
    'touch'
    'mk'
    'mj'
    'split'
    'hash'
    'size'
    'sz'
    'l'
    'l.'
    'l..'
    'lh'
    'lc'
    'l/'
    'p'
    'p.'
    'p..'
    'ph'
    'pc'
    'p/'
    'c'
    'c.'
    'c..'
    'ch'
    'cc'
    'c/'
    'd/'
    'e'
    'e.'
    'e..'
    'eh'
    'ec'
    'e/'
    'i'
    'i.'
    'i..'
    'ih'
    'ic'
    'i/'
    'g'
    'gg'
    'gitcl'
    'gpp'
    'ga'
    'gs'
    'gr'
    'grp'
    'no'
    'n'
    'nx'
    'ncc'
    'npo'
    'nu'
    'nr'
    'nt'
  )
}
